CREATE PROCEDURE INSERTAALERGENO @NOMBRE VARCHAR(100)
AS
	INSERT INTO ALERGENOS(nombre) VALUES(@NOMBRE);
GO

CREATE PROCEDURE INSERTAPLATO @NOMBRE VARCHAR(100), @DESCRIPCION VARCHAR(200), @INGREDIENTES VARCHAR(200), @ALERGENO INT, @PRECIO smallmoney
AS
	INSERT INTO PLATOS(nombre, descripcion, ingredientes, alergeno_id, precio) VALUES(@NOMBRE, @DESCRIPCION, @INGREDIENTES, @ALERGENO, @PRECIO);
GO

CREATE PROCEDURE INSERTAMESA @NUMMESA SMALLINT
AS
	INSERT INTO MESA(numeroMesa) VALUES(@NUMMESA);
GO

CREATE PROCEDURE INSERTALINEACUENTA @NUMMESA SMALLINT, @FECHA DATETIME, @PLATO VARCHAR(100), @CANTIDAD INT
AS
	--Los datos que se cogen desde la web son la fecha
	--El precio ya va con iva non hace falta calcularlo
	--PLATO es el nombre del plato

	DECLARE @MESA INT;
	DECLARE @PLATO_ID INT;
	DECLARE @PRECIO SMALLMONEY; 

	SET @MESA = (SELECT id FROM MESA WHERE numeroMesa = @NUMMESA);
	SET @PRECIO = (SELECT id FROM PLATOS WHERE nombre LIKE @PLATO) * @CANTIDAD;

	INSERT INTO CUENTAS(id_mesa, fechaCuenta, nombrePlato, cantidad, precioTotal) VALUES(@NUMMESA, @FECHA, @PLATO, @CANTIDAD, @PRECIO);
GO